---
- name: Redeploy-overcloud
  hosts: osp13-undercloud
  remote_user: stack
  gather_facts: no
  tasks:
    - name: Deploy overcloud vlan
      command: "time openstack overcloud deploy --templates --roles-file ~/templates/aci_roles_data.yaml --environment-file ~/generated-openstack-tripleo-heat-templates/environments/network-isolation.yaml --environment-file ~/templates/network-environment-overrides.yaml --environment-file ~/templates/ciscoaci_containers.yaml --environment-file ~/templates/ciscoaci-env.vlan.yaml --ntp-server 1.255.0.1"
