---
- name: Rollback
  hosts: srv1.mad.lab
  gather_facts: no
  vars_prompt:
    - name: "project-name"
      prompt: "CISCO"
      default: "CISCO"
      private: no
  tasks:
    - name: rollback
      command: "{{item}}"
      with_items:
        - openstack project create --description {{project-name}} {{project-name}}
        - openstack role add --user admin --project {{project-name}} admin
        - openstack network create {{project-name}}-NET10
        - openstack subnet create --network {{project-name}}-NET10 --subnet-range 10.0.0.0/24 {{project-name}}-SUBNET10
        - openstack router create {{project-name}}-ROUTER
        - openstack router add subnet {{project-name}}-ROUTER {{project-name}}-SUBNET10
        - openstack security group create {{project-name}}-SECURITY-GROUP
        - openstack security group rule create --proto tcp --dst-port 22 {{project-name}}-SECURITY-GROUP
        - openstack security group rule create --proto icmp {{project-name}}-SECURITY-GROUP
        - openstack server create --security-group {{project-name}}-SECURITY-GROUP --flavor small --image cirros --nic net-id={{project-name}}-NET10 {{project-name}}-1
        - openstack server create --security-group {{project-name}}-SECURITY-GROUP --flavor small --image cirros --nic net-id={{project-name}}-NET10 {{project-name}}-2
        - neutron router-gateway-set {{project-name}}-ROUTER L3OUT_AIBARRIO
