---
- name: Rollback
  hosts: srv1.mad.lab
  gather_facts: no
  vars_prompt:
    - name: "rollback"
      prompt: "01-empty"
      default: "01"
      private: no
  tasks:
    - name: rollback
      command: "{{item}}"
      with_items:
        - virsh snapshot-revert --snapshotname {{rollback}} --domain osp-director
#        - virsh snapshot-revert --snapshotname {{rollback}} --domain kb-node2
#        - virsh snapshot-revert --snapshotname {{rollback}} --domain kb-node3
#        - virsh snapshot-revert --snapshotname {{rollback}} --domain kb-node4
        - virsh start osp-director
#        - virsh start kb-node2
#        - virsh start kb-node3
#        - virsh start kb-node4
