---
- name: Prepare
  hosts: osp13-all
  gather_facts: no
  tasks:
    - name: Disabling SE linux
      command: setenforce 0
    - name: Disabling SE linux permanent
      command: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
- name: Install packages
  hosts: osp13-controller
  gather_facts: no
  tasks:
    - name: Install Packages
      yum:
        state: present
        name:
          - git
          - python-devel
          - libffi-devel
          - gcc
          - openssl-devel
          - libselinux-python
          - python-pip
