---
- name: Prepare
  hosts: osp13-all
  gather_facts: yes
  tasks:
    - name: Disabling SE linux
      command: setenforce 0
    - name: Disabling SE linux permanent
      command: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
    - name: Disable subscription
      command: sed -i "s/enabled\=aa/enabled\=0/g" /etc/yum/pluginconf.d/subscription-manager.conf
      when: (ansible_facts['distribution'] == "RedHat")
    - name: Enable local repo
      get_url:
        url: http://registry.mad.lab/local.repo
        dest: /etc/yum.repos.d/local.repo
      when: (ansible_facts['distribution'] == "RedHat")
- name: Install packages
  hosts: rh-osp13-controller
  gather_facts: no
  tasks:
    - name: Install Packages
      yum:
        state: present
        name:
          - git
          - python-devel
          - libffi-devel
          - gcc
          - openssl-devel
          - libselinux-python
          - python-pip
