---
- name: Prepare
  hosts: osp13-all
  gather_facts: no
  tasks:
    - name: Disabling SE linux
      command: setenforce 0
    - name: Disabling SE linux permanent
      command: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
- name: Install packages
  hosts: osp13-controller
  gather_facts: no
  tasks:
    - name: Install Packages
      yum:
        state: present
        name:
          - git
          - python-devel
          - libffi-devel
          - gcc
          - openssl-devel
          - libselinux-python
          - python-pip
          - ansible
    - name: Update pip
      command: pip install -U pip
    - name: Install ansible and kolla-ansible
      command: "{{item}}"
      with_items:
        - pip install ansible kolla-ansible
        - sudo mkdir -p /etc/kolla
        - sudo chown $USER:$USER /etc/kolla
    - name: Copy globals
      copy:
        src: /usr/share/kolla-ansible/etc_examples/kolla/globals.yml
        dest: /etc/kolla/globals.yml
        remote_src: yes
    - name: Copy passwords.yml
      copy:
        src: /usr/share/kolla-ansible/etc_examples/kolla/passwords.yml
        dest: /etc/kolla
        remote_src: yes
    - name: Copy passwords.yml
      copy:
        src: /usr/share/kolla-ansible/ansible/inventory/multinode
        dest: /root/
        remote_src: yes
    - name: Configure /etc/kolla/globals.yml
      lineinfile:
        path: /etc/kolla/globals.yml
        line: kolla_base_distro = "centos"
        line: kolla_install_type = "source"
        line: openstack_release = "queens"
        line: kolla_internal_vip_address = "1.1.1.26"
