---
- name: Prepare
  hosts: osp13-all
  gather_facts: no
  tasks:
    - name: Disabling SE linux
      command: setenforce 0
    - name: Disabling SE linux permanent
      command: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
- name: Install packages
  hosts: osp13-controller
  gather_facts: no
  tasks:
    - name: Install Packages
      yum:
        state: present
        name:
          - git
          - python-devel
          - libffi-devel
          - gcc
          - openssl-devel
          - libselinux-python
          - python-pip
          - ansible
    - name: Update pip
      command: pip install -U pip
    - name: Install ansible and kolla-ansible
      command: "{{item}}"
      with_items:
        - pip install ansible kolla-ansible
        - sudo mkdir -p /etc/kolla
        - sudo chown $USER:$USER /etc/kolla
        - cp -r  /usr/share/kolla-ansible/etc_examples/kolla/* /etc/kolla
        - cp /usr/share/kolla-ansible/ansible/inventory/* .
        - sed -i 's/^network_interface.*/network_interface: \"eth0\"/g' globals.yml
        - sed -i 's/^neutron_external_interface.*/neutron_external_interface: \"eth1\"/g' globals.yml
        - kolla-genpwd
        - sed -i 's/^#kolla_base_distro.*/kolla_base_distro\:\ \"centos\"/g' globals.yml
        - sed -i 's/^#kolla_install_type.*/kolla_install_type\:\ \"source\"/g' globals.yml
        - sed -i 's/^#openstack_release.*/openstack_release\:\ \"queens\"/g' globals.yml
        - sed -i 's/^kolla_internal_vip_address.*/kolla_internal_vip_address\:\ \"1.1.1.26"/g' globals.yml
    - name: DEPLOYTING Bootstrap-servers
      command: kolla-ansible -i ./multinode bootstrap-servers
