---
- name: PREPARE DOCKER # For allow insecure HTTP
  hosts: osp-director
  remote_user: root
  gather_facts: no
  tasks:
    - name: Copy deploy_project.yml
      copy:
        src: files/daemon.json
        dest: /etc/docker/daemon.json
        force: yes
    - name: Copy docker.conf
      copy:
        src: files/docker.conf
        dest: /etc/systemd/system/docker.service.d/docker.conf
        force: yes
    - name: Creating symbolic link
      command: ln -s /usr/libexec/docker/docker-runc-current /usr/libexec/docker/docker-runc
    - name: Restart systemctl daemon
      command: systemctl daemon-reload
    - name: Restart docker
      command: service docker restart
- name: PREPARE DIRECTORY
  hosts: osp-director
  remote_user: stack
  gather_facts: no
  tasks:
    - name: Copy deploy_project.yml
      copy:
        src: files/deploy_project.yml
        dest: ~/deploy_project.yml
        mode: '0774'
    - name: Copy patch
      copy:
        src: files/patch.diff
        dest: ~/patch.diff
    - name: Patch keystone.yaml
      shell: 
        cmd: sudo patch /usr/share/openstack-tripleo-heat-templates/docker/services/keystone.yaml < patch.diff
    - name: Download tripleo-ciscoaci-13.0-749.noarch.rpm
      get_url:
        url: http://registry.mad.lab/osp13/tripleo-ciscoaci-13.0-749.noarch.rpm
        dest: ~/tripleo-ciscoaci-13.0-749.noarch.rpm
    - name: Download deploy.tar
      get_url:
        url: http://registry.mad.lab/osp13/deploy.tar
        dest: ~/deploy.tar
    - name: Uncompress templates
      command: tar -xf deploy.tar
    - name: Patch keystone.yaml
      command: sudo yum localinstall tripleo-ciscoaci-13.0-749.noarch.rpm -y
    - name: copy cisco-aci-tripleo-heat-templates
      command: cp -r /opt/ciscoaci-tripleo-heat-templates .
    - name: Copy ciscoaci-env.yaml
      copy:
        src: files/ciscoaci-env.yaml
        dest: ~/templates/ciscoaci-env.yaml
- name: DEPLOY CISCO CONTAINERS
  hosts: osp-director
  remote_user: stack
  gather_facts: no
  tasks:
    - name: Create containers
      command: "{{item}}"
      with_items:
        - /opt/ciscoaci-tripleo-heat-templates/tools/build_openstack_aci_containers.py --upstream=registry.mad.lab:5000 --destregistry=192.168.24.1:8787
        - openstack role add --user admin --project service ResellerAdmin
    - name: Openstack temp-url-key
      shell:
        cmd: openstack --os-project-name service object store account set --property Temp-URL-Key=$(uuidgen | sha1sum | awk '{print $1}')
    - pause:
        prompt: "Press key"
- name: DEPLOY OPENSTACK OVERCLOUD
  hosts: osp-director
  remote_user: stack
  gather_facts: no
  tasks:
    - name: Openstack overcloud deploy
      shell:
        cmd: time openstack overcloud deploy --templates --roles-file ~/templates/aci_roles_data.yaml --environment-file ~/generated-openstack-tripleo-heat-templates/environments/network-isolation.yaml --environment-file ~/templates/network-environment-overrides.yaml --environment-file ~/templates/ciscoaci_containers.yaml --environment-file ~/templates/ciscoaci-env.yaml  --ntp-server 1.255.0.1
