---
- name: Upload Cerros Image
  hosts: osp-director
  remote_user: stack
  gather_facts: no
  tasks:
    - name: Download cirros
      command: wget http://registry.mad.lab/osp13/cirros-0.4.0-x86_64-disk.img
    - name: Upload Cerros Image
      command: glance image-create --name cirros --disk-format qcow2 --container-format bare --visibility public --file cirros-0.4.0-x86_64-disk.img
    - name: Create flavor
      command: openstack flavor create --id auto --ram 64 --vcpus 1 --public small
    - name: Create External Network
      command: neutron net-create L3OUT_AIBARRIO --router:external True --shared --apic:distinguished_names type=dict ExternalNetwork=uni/tn-common/out-L3OUT_AIBARRIO/instP-ANY
    - name: Create SNAT
      command: neutron subnet-create L3OUT_AIBARRIO 1.2.6.0/24 --name SNAT --disable-dhcp --gateway 1.2.6.1 --apic:snat_host_pool True
    - name: Create FIP
      command: openstack subnet create --subnet-range 1.2.7.0/24 --no-dhcp --gateway 1.2.7.1 --network L3OUT_AIBARRIO FIP
    - name: Delete cirros
      command: rm -rf cirros-0.4.0-x86_64-disk.img
