---
- name: Deploy project
  hosts: osp13-undercloud
  gather_facts: no
  vars_prompt:
    - name: "project"
      prompt: "CISCO"
      default: "CISCO"
      private: no
  tasks:
    - name: Create project
      command: "{{item}}"
      with_items:
        - "openstack project create --description {{project}} {{project}}"
        - "openstack role add --user admin --project {{project}} admin"
        - "openstack network create {{project}}-NET10 --project {{project}}"
        - "openstack subnet create --network {{project}}-NET10 --project {{project}} --subnet-range 10.0.0.0/24 {{project}}-SUBNET10"
        - "openstack router create {{project}}-ROUTER --project {{project}}"
        - "openstack router add subnet {{project}}-ROUTER {{project}}-SUBNET10 --project {{project}}"
        - "openstack security group create {{project}}-SECURITY-GROUP --project {{project}}"
        - "openstack security group rule create --proto tcp --dst-port 22 {{project}}-SECURITY-GROUP --project {{project}}"
        - "openstack security group rule create --proto icmp {{project}}-SECURITY-GROUP --project {{project}}"
        - "openstack server create --security-group {{project}}-SECURITY-GROUP --flavor small --image cirros --nic net-id={{project}}-NET10 {{project}}-1 --project {{project}}"
        - "openstack server create --security-group {{project}}-SECURITY-GROUP --flavor small --image cirros --nic net-id={{project}}-NET10 {{project}}-2 --project {{project}}"
        - "neutron router-gateway-set {{project}}-ROUTER L3OUT_AIBARRIO --project {{project}}"
