---
- name: Delete project
  hosts: osp13-undercloud
  gather_facts: no
  vars_prompt:
    - name: "project"
      prompt: "CISCO"
      default: "CISCO"
      private: no
  tasks:
    - name: Delete project
      command: "{{item}}"
      with_items:
        - "openstack server delete {{project}}-1"
        - "openstack server delete {{project}}-2"
        - "openstack security group rule delete --proto tcp --dst-port 22 {{project}}-SECURITY-GROUP"
        - "openstack security group rule delete --proto icmp {{project}}-SECURITY-GROUP"
        - "openstack security group delete {{project}}-SECURITY-GROUP"
        - "openstack router remove subnet {{project}}-ROUTER {{project}}-SUBNET10"
        - "openstack router delete {{project}}-ROUTER"
        - "openstack subnet delete {{project}}-SUBNET10"
        - "openstack network delete {{project}}-NET10"
        - "openstack project delete {{project}}"
        - "neutron purge {{project}}"
