---
- name: Deploy project
  hosts: osp13-undercloud
  gather_facts: no
  vars_prompt:
    - name: "project"
      prompt: "TEST"
      default: "TEST"
      private: no
  tasks:
    - name: Create project
      command: "{{item}}"
      with_items:
        - "openstack project create --description {{project}} {{project}}"
        - "openstack role add --user admin --project {{project}} admin"
  environment:
    OS_PROJECT_NAME: "{{project}}"
  tasks:
    - name: Create objects
      command: "{{item}}"
      with_items:
        - "openstack network create {{project}}-NET10"
