---
- name: Deploy TEST
  hosts: osp13-undercloud
  remote_user: stack
  gather_facts: no
  vars_prompt:
    - name: "project"
      prompt: "TEST"
      default: "TEST"
      private: no
  tasks:
#    - name: LOAD ENV FILE
#      shell: source overcloudrc
    - name: CREATE PROJECT
      command: "{{item}}"
      with_items:
        - "openstack project create --description {{project}} {{project}}"
        - "openstack role add --user admin --project {{project}} admin"
      register: result
    - debug:
        var: result.output
  environment:
    OS_PROJECT_NAME: "{{project}}"
  tasks:
    - name: CREATE OBJECTS
      command: "{{item}}"
      with_items:
        - "openstack network create {{project}}-NET10"
      register: result
    - debug:
        var: result.output
