---
- name: PREPARE SERVER
  hosts: osp-director
  remote_user: root
  gather_facts: no
  tasks:
    - name: Disable NetworkManager
      systemd:
        name: NetworkManager
        state: stopped
        enabled: no
- name: DEPLOY-UNDERCLOUD
  hosts: osp-director
  remote_user: stack
  gather_facts: no
  tasks:
    - name: Deploy overcloud vlan
      command: "{{item}}"
      with_items:
        - curl -O http://registry.mad.lab/osp13/python2-tripleo-repos-0.0.1-0.20200310031818.5aa9c9a.el7.noarch.rpm
        - sudo yum localinstall python2-tripleo-repos-0.0.1-0.20200310031818.5aa9c9a.el7.noarch.rpm  -y
        - sudo -E tripleo-repos -b queens current
        - sudo yum install -y python-tripleoclient
        - cp /usr/share/python-tripleoclient/undercloud.conf.sample ~/undercloud.conf
        - openstack undercloud install
