---
- name: PREPARE SERVER
  hosts: osp-director
  remote_user: root
  gather_facts: no
  tasks:
    - name: Disable NetworkManager
      systemd:
        state: stopped
        enabled: no
    - meta: end_play
- name: DEPLOY-UNDERCLOUD
  hosts: osp-director
  remote_user: stack
  gather_facts: no
  tasks:
    - name: Deploy overcloud vlan
      command:
